### ISSUE TITLE
[Bug] Horizontal scroll bar if I create issue

### ISSUE THREAD

**Issue by Kristinita** [divinites/gissues#84]
### Summary

I have horizontal scroll bar if I create issue.
### Expected behavior

No horizontal scroll bar.
### Actual behavior

![Horizontal scroll bar](http://i.imgur.com/CgVtQSD.png)
### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

<kbd>Ctrl+Shift+P</kbd> → `GitHub Issues: Create Issue` → `manually enter repository...` → I print any repository → if I wrote issue, I have horizontal scroll bar.
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by divinites** [comment]
Sorry, I do not understand this bug？ scroll bar appears when the layout cannot show all content

**Comment by Kristinita** [comment]
You add many new lines, but these lines not transferred to the new line. Therefore, it is horizontal scroll bar.

![New lines](http://i.imgur.com/Qy6J9gK.png)

It would be nice if users can remove these lines.

Thanks.

**Comment by divinites** [comment]
These lines are nessary to divided different parts of issues, so that the program can extract information from the view.  These lines exist before, the only difference is that before all lines use "--", now it use various symbols like "<" ">" and "~".

There are two new parameters that you can configure,  wrap_width and draw_centered, please see readme.md for details. 

I will make a small update, so that these lines can be aligned with wrap_width.

**Comment by divinites** [comment]
I think your problem is the wrap width problem, the default value is 80,  which means one line contains 80 chars, you can change it to your custom value

**Comment by Kristinita** [comment]
Thank you! I make `"wrap_width": 0` and GitHub Issues works now!

Please, not use `~~` symbols for lines, is [equivalent `strike` tag](http://webapps.stackexchange.com/a/56851/122122) for HTML.

Thanks.

**Comment by divinites** [comment]
& b20d741c62d95a21e3cec2308c19bc24e9bd2b20 addressed this issue, v 3.1.0 just released. Please see readme.md for the new configure parameter "split_line_width". @Kristinita
