### ISSUE TITLE
[Bug] Not worked move and select_all commands when I wrote issue

### ISSUE THREAD

**Issue by Kristinita** [divinites/gissues#94]
### Summary

Not worked <kbd>Ctrl+A</kbd> hotkey + <kbd>Up</kbd> key in end of issue, if I wrote issue.

### Expected behavior

Normally functioning `select_all` and `move` commands if I wrote issue.

### Actual behavior

![Actual behavior](http://i.imgur.com/I9bl0bm.gif)

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

<kbd>Ctrl+Shift+P</kbd> → `GitHub Issues: Create Issue` → I print, for example, `divinites/gissues` → <kbd>Enter</kbd>.

If I press <kbd>Ctrl+A</kbd>, text not selected for me. If I press <kbd>Up</kbd>, I can not move up, if my carriage in end of issue.

If `debug=1` for me, I see in console:

```
key evt: up
command: move {"by": "lines", "forward": false}
GitHub Issue >>> current cursor is located at 1160
GitHub Issue >>> find the row 47 and the col 16
```

```
key evt: control+a
command: select_all
GitHub Issue >>> current cursor is located at 0
GitHub Issue >>> find the row 0 and the col 0
GitHub Issue >>> starting pushing back the cursor
GitHub Issue >>> push back the cursor to 18
```

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by divinites** [comment]
done.

**Comment by divinites** [comment]
which screen recording software you are using? Seems much better than what I have...

**Comment by Kristinita** [comment]
> which screen recording software you are using? Seems much better than what I have...
- [ScreenToGIF](https://github.com/NickeManarin/ScreenToGif),
- [KeypressOSD AutoHotkey script](https://autohotkey.com/boards/viewtopic.php?t=225).

But its all only for Windows.

Thanks.

**Comment by divinites** [comment]
Thanks. I am afraid I have to stick to what I have then. The problem of this bug is because I do not want users to modified the split lines and header prompts, so the cursor will be push back when user clicking these regions. This leads to a side-effect, as you pointed out, ctrl+a no more works.

So what I do now is to use another workaround: when user's cursor are in these "unmodifiable" region, the whole view will switch to read-only, and it will switch back when the cursor moves out from these protected area.

**Comment by Kristinita** [comment]
@divinites #101 $ 8c8c08a2d1686aaa745f5fd29376b2c4ce67231c
